export default {
  'Inter-Black': require('./Inter_18pt-Black.ttf'),
  'Inter-Bold': require('./Inter_18pt-Bold.ttf'),
  'Inter-ExtraBold': require('./Inter_18pt-ExtraBold.ttf'),
  'Inter-ExtraLight': require('./Inter_18pt-ExtraLight.ttf'),
  'Inter-Light': require('./Inter_18pt-Light.ttf'),
  'Inter-Medium': require('./Inter_18pt-Medium.ttf'),
  'Inter-Regular': require('./Inter_18pt-Regular.ttf'),
  'Inter-SemiBold': require('./Inter_18pt-SemiBold.ttf'),
  'Inter-Thin': require('./Inter_18pt-Thin.ttf'),
  'LexendDeca-Black': require('./LexendDeca-Black.ttf'),
  'LexendDeca-Bold': require('./LexendDeca-Bold.ttf'),
  'LexendDeca-ExtraBold': require('./LexendDeca-ExtraBold.ttf'),
  'LexendDeca-ExtraLight': require('./LexendDeca-ExtraLight.ttf'),
  'LexendDeca-Light': require('./LexendDeca-Light.ttf'),
  'LexendDeca-Medium': require('./LexendDeca-Medium.ttf'),
  'LexendDeca-Regular': require('./LexendDeca-Regular.ttf'),
  'LexendDeca-SemiBold': require('./LexendDeca-SemiBold.ttf'),
  'LexendDeca-Thin': require('./LexendDeca-Thin.ttf'),
};
